import type { BrandingSettings } from "./branding.types";

export const FALLBACK_BRANDING: BrandingSettings = {
  id: "fallback-id",
  company_name: "Shafsky Aviation Services",
  company_tagline: "Welcome Begins Before You Land.",
  website: "https://shafskyaviation.com",
  booking_email: "bookings@shafskyaviation.com",
  support_email: "support@shafskyaviation.com",
  reply_email: "concierge@shafskyaviation.com",
  support_phone: "+91 9599087959",
  whatsapp_number: "+91 95990 87959",
  business_address: "8/5, Ground Floor, West Mehram Nagar Gate No.1, Opp. IGI Airport Terminal 1",
  city: "New Delhi",
  state: "Delhi",
  country: "India",
  postal_code: "110010",
  logo_url: "/logo.png",
  logo_dark_url: "/logo.png",
  logo_light_url: "/logo.png",
  favicon_url: "/favicon.ico",
  primary_color: "#0d2a36",
  secondary_color: "#c5a059",
  accent_color: "#5ed3ff",
  linkedin_url: "https://www.linkedin.com/in/mohammad-shahood-shafsky",
  facebook_url: "https://www.facebook.com/shafskyaviation/",
  instagram_url: "https://www.instagram.com/aviationshafsky/",
  youtube_url: "https://www.youtube.com/@shafskyaviation",
  twitter_url: "https://x.com/ShafskyAviation",
  copyright_text: "© 2026 Shafsky Aviation Services Pvt. Ltd. All Rights Reserved.",
  is_active: true,
};
