import { BookingService, ServiceCategory, ServiceDescriptor } from "../types/service.types";

export const SERVICES_CONFIG: Record<BookingService, ServiceDescriptor> = {
  [BookingService.MEET_GREET]: {
    id: BookingService.MEET_GREET,
    displayName: "Airport Meet & Greet",
    category: ServiceCategory.AIRPORT,
    requiresFlight: true,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.LOUNGE]: {
    id: BookingService.LOUNGE,
    displayName: "VIP Airport Lounge",
    category: ServiceCategory.AIRPORT,
    requiresFlight: false,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.FAST_TRACK]: {
    id: BookingService.FAST_TRACK,
    displayName: "Immigration Fast Track",
    category: ServiceCategory.AIRPORT,
    requiresFlight: true,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.TRANSFER]: {
    id: BookingService.TRANSFER,
    displayName: "Chauffeur Airport Transfer",
    category: ServiceCategory.AIRPORT,
    requiresFlight: false,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: true,
  },
  [BookingService.HOTEL]: {
    id: BookingService.HOTEL,
    displayName: "Luxury Hotel Suite Booking",
    category: ServiceCategory.TRAVEL,
    requiresFlight: false,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: true,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.VISA]: {
    id: BookingService.VISA,
    displayName: "Diplomatic Visa Assistance",
    category: ServiceCategory.TRAVEL,
    requiresFlight: false,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: true,
    requiresTransfer: false,
  },
  [BookingService.TICKETING]: {
    id: BookingService.TICKETING,
    displayName: "Commercial Air Ticketing",
    category: ServiceCategory.TRAVEL,
    requiresFlight: true,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.MEALS]: {
    id: BookingService.MEALS,
    displayName: "Gourmet Inflight Meals",
    category: ServiceCategory.TRAVEL,
    requiresFlight: false,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.CARGO]: {
    id: BookingService.CARGO,
    displayName: "General Air Cargo Freight",
    category: ServiceCategory.LOGISTICS,
    requiresFlight: false,
    requiresPassengers: false,
    requiresMedical: false,
    requiresCargo: true,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.AVI]: {
    id: BookingService.AVI,
    displayName: "Live Animal Pet Transport",
    category: ServiceCategory.LOGISTICS,
    requiresFlight: false,
    requiresPassengers: false,
    requiresMedical: false,
    requiresCargo: true,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.AIR_AMBULANCE]: {
    id: BookingService.AIR_AMBULANCE,
    displayName: "Airborne ICU Air Ambulance",
    category: ServiceCategory.MEDICAL,
    requiresFlight: false,
    requiresPassengers: false,
    requiresMedical: true,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.TRAIN_AMBULANCE]: {
    id: BookingService.TRAIN_AMBULANCE,
    displayName: "Medical Train Compartment Transfer",
    category: ServiceCategory.MEDICAL,
    requiresFlight: false,
    requiresPassengers: false,
    requiresMedical: true,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.HUM]: {
    id: BookingService.HUM,
    displayName: "Dignified Mortal Remains Repatriation",
    category: ServiceCategory.MEDICAL,
    requiresFlight: false,
    requiresPassengers: false,
    requiresMedical: true,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
  [BookingService.CHARTER]: {
    id: BookingService.CHARTER,
    displayName: "Private Jet Charter Flight",
    category: ServiceCategory.CHARTER,
    requiresFlight: true,
    requiresPassengers: true,
    requiresMedical: false,
    requiresCargo: false,
    requiresHotel: false,
    requiresVisa: false,
    requiresTransfer: false,
  },
};
