/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AirportsRouteImport } from './routes/airports'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as CharterRouteImport } from './routes/charter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlightVerificationRouteImport } from './routes/flight-verification'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AirportsCodeRouteImport } from './routes/airports.$code'
import { Route as ApiProcessQueueRouteImport } from './routes/api.process-queue'
import { Route as ServicesGuideRouteImport } from './routes/services.guide'
import { Route as SolutionsAviationRouteImport } from './routes/solutions.aviation'
import { Route as SolutionsCargoRouteImport } from './routes/solutions.cargo'
import { Route as SolutionsConciergeRouteImport } from './routes/solutions.concierge'
import { Route as SolutionsMedicalRouteImport } from './routes/solutions.medical'
import { Route as SolutionsTravelRouteImport } from './routes/solutions.travel'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminCasesRouteImport } from './routes/_authenticated/admin.cases'
import { Route as AuthenticatedAdminCharterRouteImport } from './routes/_authenticated/admin.charter'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminFlightsRouteImport } from './routes/_authenticated/admin.flights'
import { Route as AuthenticatedAdminLoungesRouteImport } from './routes/_authenticated/admin.lounges'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminOperationsRouteImport } from './routes/_authenticated/admin.operations'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin.index'
import { Route as AuthenticatedSuperAdminAdminsRouteImport } from './routes/_authenticated/super-admin.admins'
import { Route as AuthenticatedSuperAdminAirportsRouteImport } from './routes/_authenticated/super-admin.airports'
import { Route as AuthenticatedSuperAdminAuditLogsRouteImport } from './routes/_authenticated/super-admin.audit-logs'
import { Route as AuthenticatedSuperAdminBrandingRouteImport } from './routes/_authenticated/super-admin.branding'
import { Route as AuthenticatedSuperAdminCouponsRouteImport } from './routes/_authenticated/super-admin.coupons'
import { Route as AuthenticatedSuperAdminLoungesRouteImport } from './routes/_authenticated/super-admin.lounges'
import { Route as AuthenticatedSuperAdminPaymentsRouteImport } from './routes/_authenticated/super-admin.payments'
import { Route as AuthenticatedSuperAdminPermissionsRouteImport } from './routes/_authenticated/super-admin.permissions'
import { Route as AuthenticatedSuperAdminRolesRouteImport } from './routes/_authenticated/super-admin.roles'
import { Route as AuthenticatedSuperAdminSecurityRouteImport } from './routes/_authenticated/super-admin.security'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated/super-admin.settings'
import { Route as AuthenticatedSuperAdminSystemRouteImport } from './routes/_authenticated/super-admin.system'
import { Route as AuthenticatedSuperAdminUsersRouteImport } from './routes/_authenticated/super-admin.users'
import { Route as ApiCharterRequestsRouteImport } from './routes/api.charter.requests'
import { Route as ApiFlightValidateRouteImport } from './routes/api.flight.validate'
import { Route as AuthenticatedAdminBookingsIdRouteImport } from './routes/_authenticated/admin.bookings.$id'
import { Route as ApiV1CharterRequestsRouteImport } from './routes/api.v1.charter.requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsRoute = AirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterRoute = CharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightVerificationRoute = FlightVerificationRouteImport.update({
  id: '/flight-verification',
  path: '/flight-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AirportsCodeRoute = AirportsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AirportsRoute,
} as any)
const ApiProcessQueueRoute = ApiProcessQueueRouteImport.update({
  id: '/api/process-queue',
  path: '/api/process-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGuideRoute = ServicesGuideRouteImport.update({
  id: '/services/guide',
  path: '/services/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAviationRoute = SolutionsAviationRouteImport.update({
  id: '/solutions/aviation',
  path: '/solutions/aviation',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCargoRoute = SolutionsCargoRouteImport.update({
  id: '/solutions/cargo',
  path: '/solutions/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsConciergeRoute = SolutionsConciergeRouteImport.update({
  id: '/solutions/concierge',
  path: '/solutions/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsMedicalRoute = SolutionsMedicalRouteImport.update({
  id: '/solutions/medical',
  path: '/solutions/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTravelRoute = SolutionsTravelRouteImport.update({
  id: '/solutions/travel',
  path: '/solutions/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCasesRoute = AuthenticatedAdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCharterRoute =
  AuthenticatedAdminCharterRouteImport.update({
    id: '/charter',
    path: '/charter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFlightsRoute =
  AuthenticatedAdminFlightsRouteImport.update({
    id: '/flights',
    path: '/flights',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLoungesRoute =
  AuthenticatedAdminLoungesRouteImport.update({
    id: '/lounges',
    path: '/lounges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOperationsRoute =
  AuthenticatedAdminOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAdminsRoute =
  AuthenticatedSuperAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAirportsRoute =
  AuthenticatedSuperAdminAirportsRouteImport.update({
    id: '/airports',
    path: '/airports',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAuditLogsRoute =
  AuthenticatedSuperAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminBrandingRoute =
  AuthenticatedSuperAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminCouponsRoute =
  AuthenticatedSuperAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminLoungesRoute =
  AuthenticatedSuperAdminLoungesRouteImport.update({
    id: '/lounges',
    path: '/lounges',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminPaymentsRoute =
  AuthenticatedSuperAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminPermissionsRoute =
  AuthenticatedSuperAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminRolesRoute =
  AuthenticatedSuperAdminRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSecurityRoute =
  AuthenticatedSuperAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSystemRoute =
  AuthenticatedSuperAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const ApiCharterRequestsRoute = ApiCharterRequestsRouteImport.update({
  id: '/api/charter/requests',
  path: '/api/charter/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlightValidateRoute = ApiFlightValidateRouteImport.update({
  id: '/api/flight/validate',
  path: '/api/flight/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBookingsIdRoute =
  AuthenticatedAdminBookingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBookingsRoute,
  } as any)
const ApiV1CharterRequestsRoute = ApiV1CharterRequestsRouteImport.update({
  id: '/api/v1/charter/requests',
  path: '/api/v1/charter/requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/airports': typeof AirportsRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/flight-verification': typeof FlightVerificationRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/airports/$code': typeof AirportsCodeRoute
  '/api/process-queue': typeof ApiProcessQueueRoute
  '/services/guide': typeof ServicesGuideRoute
  '/solutions/aviation': typeof SolutionsAviationRoute
  '/solutions/cargo': typeof SolutionsCargoRoute
  '/solutions/concierge': typeof SolutionsConciergeRoute
  '/solutions/medical': typeof SolutionsMedicalRoute
  '/solutions/travel': typeof SolutionsTravelRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/admin/charter': typeof AuthenticatedAdminCharterRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/admin/lounges': typeof AuthenticatedAdminLoungesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/super-admin/airports': typeof AuthenticatedSuperAdminAirportsRoute
  '/super-admin/audit-logs': typeof AuthenticatedSuperAdminAuditLogsRoute
  '/super-admin/branding': typeof AuthenticatedSuperAdminBrandingRoute
  '/super-admin/coupons': typeof AuthenticatedSuperAdminCouponsRoute
  '/super-admin/lounges': typeof AuthenticatedSuperAdminLoungesRoute
  '/super-admin/payments': typeof AuthenticatedSuperAdminPaymentsRoute
  '/super-admin/permissions': typeof AuthenticatedSuperAdminPermissionsRoute
  '/super-admin/roles': typeof AuthenticatedSuperAdminRolesRoute
  '/super-admin/security': typeof AuthenticatedSuperAdminSecurityRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/system': typeof AuthenticatedSuperAdminSystemRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/api/charter/requests': typeof ApiCharterRequestsRoute
  '/api/flight/validate': typeof ApiFlightValidateRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/api/v1/charter/requests': typeof ApiV1CharterRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/airports': typeof AirportsRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/flight-verification': typeof FlightVerificationRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/airports/$code': typeof AirportsCodeRoute
  '/api/process-queue': typeof ApiProcessQueueRoute
  '/services/guide': typeof ServicesGuideRoute
  '/solutions/aviation': typeof SolutionsAviationRoute
  '/solutions/cargo': typeof SolutionsCargoRoute
  '/solutions/concierge': typeof SolutionsConciergeRoute
  '/solutions/medical': typeof SolutionsMedicalRoute
  '/solutions/travel': typeof SolutionsTravelRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/admin/charter': typeof AuthenticatedAdminCharterRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/admin/lounges': typeof AuthenticatedAdminLoungesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/super-admin/airports': typeof AuthenticatedSuperAdminAirportsRoute
  '/super-admin/audit-logs': typeof AuthenticatedSuperAdminAuditLogsRoute
  '/super-admin/branding': typeof AuthenticatedSuperAdminBrandingRoute
  '/super-admin/coupons': typeof AuthenticatedSuperAdminCouponsRoute
  '/super-admin/lounges': typeof AuthenticatedSuperAdminLoungesRoute
  '/super-admin/payments': typeof AuthenticatedSuperAdminPaymentsRoute
  '/super-admin/permissions': typeof AuthenticatedSuperAdminPermissionsRoute
  '/super-admin/roles': typeof AuthenticatedSuperAdminRolesRoute
  '/super-admin/security': typeof AuthenticatedSuperAdminSecurityRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/system': typeof AuthenticatedSuperAdminSystemRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/api/charter/requests': typeof ApiCharterRequestsRoute
  '/api/flight/validate': typeof ApiFlightValidateRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/api/v1/charter/requests': typeof ApiV1CharterRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/airports': typeof AirportsRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/flight-verification': typeof FlightVerificationRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/airports/$code': typeof AirportsCodeRoute
  '/api/process-queue': typeof ApiProcessQueueRoute
  '/services/guide': typeof ServicesGuideRoute
  '/solutions/aviation': typeof SolutionsAviationRoute
  '/solutions/cargo': typeof SolutionsCargoRoute
  '/solutions/concierge': typeof SolutionsConciergeRoute
  '/solutions/medical': typeof SolutionsMedicalRoute
  '/solutions/travel': typeof SolutionsTravelRoute
  '/verify/$id': typeof VerifyIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/_authenticated/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/_authenticated/admin/charter': typeof AuthenticatedAdminCharterRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/_authenticated/admin/lounges': typeof AuthenticatedAdminLoungesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/_authenticated/super-admin/airports': typeof AuthenticatedSuperAdminAirportsRoute
  '/_authenticated/super-admin/audit-logs': typeof AuthenticatedSuperAdminAuditLogsRoute
  '/_authenticated/super-admin/branding': typeof AuthenticatedSuperAdminBrandingRoute
  '/_authenticated/super-admin/coupons': typeof AuthenticatedSuperAdminCouponsRoute
  '/_authenticated/super-admin/lounges': typeof AuthenticatedSuperAdminLoungesRoute
  '/_authenticated/super-admin/payments': typeof AuthenticatedSuperAdminPaymentsRoute
  '/_authenticated/super-admin/permissions': typeof AuthenticatedSuperAdminPermissionsRoute
  '/_authenticated/super-admin/roles': typeof AuthenticatedSuperAdminRolesRoute
  '/_authenticated/super-admin/security': typeof AuthenticatedSuperAdminSecurityRoute
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/super-admin/system': typeof AuthenticatedSuperAdminSystemRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/api/charter/requests': typeof ApiCharterRequestsRoute
  '/api/flight/validate': typeof ApiFlightValidateRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/api/v1/charter/requests': typeof ApiV1CharterRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/airports'
    | '/auth'
    | '/book'
    | '/charter'
    | '/contact'
    | '/flight-verification'
    | '/gallery'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/super-admin'
    | '/airports/$code'
    | '/api/process-queue'
    | '/services/guide'
    | '/solutions/aviation'
    | '/solutions/cargo'
    | '/solutions/concierge'
    | '/solutions/medical'
    | '/solutions/travel'
    | '/verify/$id'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/cases'
    | '/admin/charter'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/flights'
    | '/admin/lounges'
    | '/admin/notifications'
    | '/admin/operations'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/super-admin/admins'
    | '/super-admin/airports'
    | '/super-admin/audit-logs'
    | '/super-admin/branding'
    | '/super-admin/coupons'
    | '/super-admin/lounges'
    | '/super-admin/payments'
    | '/super-admin/permissions'
    | '/super-admin/roles'
    | '/super-admin/security'
    | '/super-admin/settings'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/api/charter/requests'
    | '/api/flight/validate'
    | '/admin/'
    | '/super-admin/'
    | '/admin/bookings/$id'
    | '/api/v1/charter/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/airports'
    | '/auth'
    | '/book'
    | '/charter'
    | '/contact'
    | '/flight-verification'
    | '/gallery'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dashboard'
    | '/airports/$code'
    | '/api/process-queue'
    | '/services/guide'
    | '/solutions/aviation'
    | '/solutions/cargo'
    | '/solutions/concierge'
    | '/solutions/medical'
    | '/solutions/travel'
    | '/verify/$id'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/cases'
    | '/admin/charter'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/flights'
    | '/admin/lounges'
    | '/admin/notifications'
    | '/admin/operations'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/super-admin/admins'
    | '/super-admin/airports'
    | '/super-admin/audit-logs'
    | '/super-admin/branding'
    | '/super-admin/coupons'
    | '/super-admin/lounges'
    | '/super-admin/payments'
    | '/super-admin/permissions'
    | '/super-admin/roles'
    | '/super-admin/security'
    | '/super-admin/settings'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/api/charter/requests'
    | '/api/flight/validate'
    | '/admin'
    | '/super-admin'
    | '/admin/bookings/$id'
    | '/api/v1/charter/requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/airports'
    | '/auth'
    | '/book'
    | '/charter'
    | '/contact'
    | '/flight-verification'
    | '/gallery'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/super-admin'
    | '/airports/$code'
    | '/api/process-queue'
    | '/services/guide'
    | '/solutions/aviation'
    | '/solutions/cargo'
    | '/solutions/concierge'
    | '/solutions/medical'
    | '/solutions/travel'
    | '/verify/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/cases'
    | '/_authenticated/admin/charter'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/flights'
    | '/_authenticated/admin/lounges'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/operations'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/super-admin/admins'
    | '/_authenticated/super-admin/airports'
    | '/_authenticated/super-admin/audit-logs'
    | '/_authenticated/super-admin/branding'
    | '/_authenticated/super-admin/coupons'
    | '/_authenticated/super-admin/lounges'
    | '/_authenticated/super-admin/payments'
    | '/_authenticated/super-admin/permissions'
    | '/_authenticated/super-admin/roles'
    | '/_authenticated/super-admin/security'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/super-admin/system'
    | '/_authenticated/super-admin/users'
    | '/api/charter/requests'
    | '/api/flight/validate'
    | '/_authenticated/admin/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/admin/bookings/$id'
    | '/api/v1/charter/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AirportsRoute: typeof AirportsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  CharterRoute: typeof CharterRoute
  ContactRoute: typeof ContactRoute
  FlightVerificationRoute: typeof FlightVerificationRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiProcessQueueRoute: typeof ApiProcessQueueRoute
  ServicesGuideRoute: typeof ServicesGuideRoute
  SolutionsAviationRoute: typeof SolutionsAviationRoute
  SolutionsCargoRoute: typeof SolutionsCargoRoute
  SolutionsConciergeRoute: typeof SolutionsConciergeRoute
  SolutionsMedicalRoute: typeof SolutionsMedicalRoute
  SolutionsTravelRoute: typeof SolutionsTravelRoute
  VerifyIdRoute: typeof VerifyIdRoute
  ApiCharterRequestsRoute: typeof ApiCharterRequestsRoute
  ApiFlightValidateRoute: typeof ApiFlightValidateRoute
  ApiV1CharterRequestsRoute: typeof ApiV1CharterRequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports': {
      id: '/airports'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter': {
      id: '/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof CharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-verification': {
      id: '/flight-verification'
      path: '/flight-verification'
      fullPath: '/flight-verification'
      preLoaderRoute: typeof FlightVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/airports/$code': {
      id: '/airports/$code'
      path: '/$code'
      fullPath: '/airports/$code'
      preLoaderRoute: typeof AirportsCodeRouteImport
      parentRoute: typeof AirportsRoute
    }
    '/api/process-queue': {
      id: '/api/process-queue'
      path: '/api/process-queue'
      fullPath: '/api/process-queue'
      preLoaderRoute: typeof ApiProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/guide': {
      id: '/services/guide'
      path: '/services/guide'
      fullPath: '/services/guide'
      preLoaderRoute: typeof ServicesGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/aviation': {
      id: '/solutions/aviation'
      path: '/solutions/aviation'
      fullPath: '/solutions/aviation'
      preLoaderRoute: typeof SolutionsAviationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/cargo': {
      id: '/solutions/cargo'
      path: '/solutions/cargo'
      fullPath: '/solutions/cargo'
      preLoaderRoute: typeof SolutionsCargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/concierge': {
      id: '/solutions/concierge'
      path: '/solutions/concierge'
      fullPath: '/solutions/concierge'
      preLoaderRoute: typeof SolutionsConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/medical': {
      id: '/solutions/medical'
      path: '/solutions/medical'
      fullPath: '/solutions/medical'
      preLoaderRoute: typeof SolutionsMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/travel': {
      id: '/solutions/travel'
      path: '/solutions/travel'
      fullPath: '/solutions/travel'
      preLoaderRoute: typeof SolutionsTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cases': {
      id: '/_authenticated/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AuthenticatedAdminCasesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/charter': {
      id: '/_authenticated/admin/charter'
      path: '/charter'
      fullPath: '/admin/charter'
      preLoaderRoute: typeof AuthenticatedAdminCharterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/flights': {
      id: '/_authenticated/admin/flights'
      path: '/flights'
      fullPath: '/admin/flights'
      preLoaderRoute: typeof AuthenticatedAdminFlightsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lounges': {
      id: '/_authenticated/admin/lounges'
      path: '/lounges'
      fullPath: '/admin/lounges'
      preLoaderRoute: typeof AuthenticatedAdminLoungesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/operations': {
      id: '/_authenticated/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/admins': {
      id: '/_authenticated/super-admin/admins'
      path: '/admins'
      fullPath: '/super-admin/admins'
      preLoaderRoute: typeof AuthenticatedSuperAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/airports': {
      id: '/_authenticated/super-admin/airports'
      path: '/airports'
      fullPath: '/super-admin/airports'
      preLoaderRoute: typeof AuthenticatedSuperAdminAirportsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/audit-logs': {
      id: '/_authenticated/super-admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedSuperAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/branding': {
      id: '/_authenticated/super-admin/branding'
      path: '/branding'
      fullPath: '/super-admin/branding'
      preLoaderRoute: typeof AuthenticatedSuperAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/coupons': {
      id: '/_authenticated/super-admin/coupons'
      path: '/coupons'
      fullPath: '/super-admin/coupons'
      preLoaderRoute: typeof AuthenticatedSuperAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/lounges': {
      id: '/_authenticated/super-admin/lounges'
      path: '/lounges'
      fullPath: '/super-admin/lounges'
      preLoaderRoute: typeof AuthenticatedSuperAdminLoungesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/payments': {
      id: '/_authenticated/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof AuthenticatedSuperAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/permissions': {
      id: '/_authenticated/super-admin/permissions'
      path: '/permissions'
      fullPath: '/super-admin/permissions'
      preLoaderRoute: typeof AuthenticatedSuperAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/roles': {
      id: '/_authenticated/super-admin/roles'
      path: '/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof AuthenticatedSuperAdminRolesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/security': {
      id: '/_authenticated/super-admin/security'
      path: '/security'
      fullPath: '/super-admin/security'
      preLoaderRoute: typeof AuthenticatedSuperAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/system': {
      id: '/_authenticated/super-admin/system'
      path: '/system'
      fullPath: '/super-admin/system'
      preLoaderRoute: typeof AuthenticatedSuperAdminSystemRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/api/charter/requests': {
      id: '/api/charter/requests'
      path: '/api/charter/requests'
      fullPath: '/api/charter/requests'
      preLoaderRoute: typeof ApiCharterRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flight/validate': {
      id: '/api/flight/validate'
      path: '/api/flight/validate'
      fullPath: '/api/flight/validate'
      preLoaderRoute: typeof ApiFlightValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/bookings/$id': {
      id: '/_authenticated/admin/bookings/$id'
      path: '/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIdRouteImport
      parentRoute: typeof AuthenticatedAdminBookingsRoute
    }
    '/api/v1/charter/requests': {
      id: '/api/v1/charter/requests'
      path: '/api/v1/charter/requests'
      fullPath: '/api/v1/charter/requests'
      preLoaderRoute: typeof ApiV1CharterRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminBookingsRouteChildren {
  AuthenticatedAdminBookingsIdRoute: typeof AuthenticatedAdminBookingsIdRoute
}

const AuthenticatedAdminBookingsRouteChildren: AuthenticatedAdminBookingsRouteChildren =
  {
    AuthenticatedAdminBookingsIdRoute: AuthenticatedAdminBookingsIdRoute,
  }

const AuthenticatedAdminBookingsRouteWithChildren =
  AuthenticatedAdminBookingsRoute._addFileChildren(
    AuthenticatedAdminBookingsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRouteWithChildren
  AuthenticatedAdminCasesRoute: typeof AuthenticatedAdminCasesRoute
  AuthenticatedAdminCharterRoute: typeof AuthenticatedAdminCharterRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFlightsRoute: typeof AuthenticatedAdminFlightsRoute
  AuthenticatedAdminLoungesRoute: typeof AuthenticatedAdminLoungesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOperationsRoute: typeof AuthenticatedAdminOperationsRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRouteWithChildren,
  AuthenticatedAdminCasesRoute: AuthenticatedAdminCasesRoute,
  AuthenticatedAdminCharterRoute: AuthenticatedAdminCharterRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFlightsRoute: AuthenticatedAdminFlightsRoute,
  AuthenticatedAdminLoungesRoute: AuthenticatedAdminLoungesRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOperationsRoute: AuthenticatedAdminOperationsRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminAdminsRoute: typeof AuthenticatedSuperAdminAdminsRoute
  AuthenticatedSuperAdminAirportsRoute: typeof AuthenticatedSuperAdminAirportsRoute
  AuthenticatedSuperAdminAuditLogsRoute: typeof AuthenticatedSuperAdminAuditLogsRoute
  AuthenticatedSuperAdminBrandingRoute: typeof AuthenticatedSuperAdminBrandingRoute
  AuthenticatedSuperAdminCouponsRoute: typeof AuthenticatedSuperAdminCouponsRoute
  AuthenticatedSuperAdminLoungesRoute: typeof AuthenticatedSuperAdminLoungesRoute
  AuthenticatedSuperAdminPaymentsRoute: typeof AuthenticatedSuperAdminPaymentsRoute
  AuthenticatedSuperAdminPermissionsRoute: typeof AuthenticatedSuperAdminPermissionsRoute
  AuthenticatedSuperAdminRolesRoute: typeof AuthenticatedSuperAdminRolesRoute
  AuthenticatedSuperAdminSecurityRoute: typeof AuthenticatedSuperAdminSecurityRoute
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedSuperAdminSystemRoute: typeof AuthenticatedSuperAdminSystemRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminAdminsRoute: AuthenticatedSuperAdminAdminsRoute,
    AuthenticatedSuperAdminAirportsRoute: AuthenticatedSuperAdminAirportsRoute,
    AuthenticatedSuperAdminAuditLogsRoute:
      AuthenticatedSuperAdminAuditLogsRoute,
    AuthenticatedSuperAdminBrandingRoute: AuthenticatedSuperAdminBrandingRoute,
    AuthenticatedSuperAdminCouponsRoute: AuthenticatedSuperAdminCouponsRoute,
    AuthenticatedSuperAdminLoungesRoute: AuthenticatedSuperAdminLoungesRoute,
    AuthenticatedSuperAdminPaymentsRoute: AuthenticatedSuperAdminPaymentsRoute,
    AuthenticatedSuperAdminPermissionsRoute:
      AuthenticatedSuperAdminPermissionsRoute,
    AuthenticatedSuperAdminRolesRoute: AuthenticatedSuperAdminRolesRoute,
    AuthenticatedSuperAdminSecurityRoute: AuthenticatedSuperAdminSecurityRoute,
    AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
    AuthenticatedSuperAdminSystemRoute: AuthenticatedSuperAdminSystemRoute,
    AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AirportsRouteChildren {
  AirportsCodeRoute: typeof AirportsCodeRoute
}

const AirportsRouteChildren: AirportsRouteChildren = {
  AirportsCodeRoute: AirportsCodeRoute,
}

const AirportsRouteWithChildren = AirportsRoute._addFileChildren(
  AirportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AirportsRoute: AirportsRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  CharterRoute: CharterRoute,
  ContactRoute: ContactRoute,
  FlightVerificationRoute: FlightVerificationRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiProcessQueueRoute: ApiProcessQueueRoute,
  ServicesGuideRoute: ServicesGuideRoute,
  SolutionsAviationRoute: SolutionsAviationRoute,
  SolutionsCargoRoute: SolutionsCargoRoute,
  SolutionsConciergeRoute: SolutionsConciergeRoute,
  SolutionsMedicalRoute: SolutionsMedicalRoute,
  SolutionsTravelRoute: SolutionsTravelRoute,
  VerifyIdRoute: VerifyIdRoute,
  ApiCharterRequestsRoute: ApiCharterRequestsRoute,
  ApiFlightValidateRoute: ApiFlightValidateRoute,
  ApiV1CharterRequestsRoute: ApiV1CharterRequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
