// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export function isSupabaseConfigured(): boolean {
  const url =
    (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_URL) ||
    (typeof process !== "undefined" && process.env?.SUPABASE_URL);
  const key =
    (typeof import.meta !== "undefined" &&
      (import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env?.VITE_SUPABASE_ANON_KEY)) ||
    (typeof process !== "undefined" &&
      (process.env?.SUPABASE_PUBLISHABLE_KEY || process.env?.SUPABASE_ANON_KEY));
  return Boolean(url && key);
}

/**
 * Warn when the Supabase URL and key belong to different projects.
 *
 * A key is only valid against its own project, so a mismatch means every request
 * is rejected. That failure is otherwise silent because callers fall back to a
 * no-op client, so name the exact mismatch loudly here.
 *
 * Diagnostic only: it does not throw, so a misconfigured environment keeps the
 * same runtime behaviour it has today.
 */
function warnOnSupabaseProjectMismatch(url: string, key: string): void {
  try {
    const match = url.match(/^https:\/\/([a-z0-9-]+)\.supabase\.co/i);
    if (!match) return;
    const urlRef = match[1];
    const parts = key.split(".");
    if (parts.length !== 3) return; // opaque new-style key, cannot inspect
    const b64 = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    const padded = b64 + "=".repeat((4 - (b64.length % 4)) % 4);
    const json =
      typeof atob === "function"
        ? atob(padded)
        : Buffer.from(padded, "base64").toString("utf8");
    const payload = JSON.parse(json);
    const keyRef = typeof payload?.ref === "string" ? payload.ref : null;
    if (!keyRef || keyRef === urlRef) return;
    console.error(
      `[Supabase] Project mismatch: URL points at "${urlRef}" but the key belongs to "${keyRef}". `+
        "Supabase requests will be rejected. Align VITE_SUPABASE_URL with the key, " +
        "or swap in the key for the project the URL names.",
    );
  } catch {
    // Never let a diagnostic break client construction.
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_URL) ||
    (typeof process !== "undefined" && process.env?.SUPABASE_URL);
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== "undefined" &&
      (import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env?.VITE_SUPABASE_ANON_KEY)) ||
    (typeof process !== "undefined" &&
      (process.env?.SUPABASE_PUBLISHABLE_KEY || process.env?.SUPABASE_ANON_KEY));

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please check your .env configuration.`;
    console.warn(`[Supabase] ${message}`);
    return null;
  }

  warnOnSupabaseProjectMismatch(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createClient<Database>> | null | undefined;

function createSafeChain(): any {
  const target = () => createSafeChain();
  return new Proxy(target, {
    get(_, prop) {
      if (prop === "then") {
        return (resolve: (v: any) => void) => resolve({ data: null, error: null, count: 0 });
      }
      if (prop === "data") return { publicUrl: "" };
      if (prop === "error") return null;
      if (prop === "count") return 0;
      if (prop === "publicUrl") return "";
      return createSafeChain();
    },
    apply() {
      return createSafeChain();
    },
  });
}

const fallbackStorage = {
  from: () => ({
    createSignedUrl: async () => ({ data: null, error: null }),
    createSignedUrls: async () => ({ data: [], error: null }),
    getPublicUrl: () => ({ data: { publicUrl: "" } }),
    upload: async () => ({ data: null, error: null }),
  }),
};

const fallbackAuth = {
  getSession: async () => ({ data: { session: null }, error: null }),
  getUser: async () => ({ data: { user: null }, error: null }),
  onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
  signOut: async () => ({ error: null }),
};

export const supabase = new Proxy({} as any, {
  get(_, prop, receiver) {
    if (!isSupabaseConfigured()) {
      if (prop === "auth") return fallbackAuth;
      if (prop === "storage") return fallbackStorage;
      if (prop === "channel") {
        return () => ({
          on: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }),
          subscribe: () => ({ unsubscribe: () => {} }),
        });
      }
      if (prop === "removeChannel") return () => {};
      if (prop === "from") return () => createSafeChain();
      return createSafeChain();
    }
    if (_supabase === undefined) _supabase = createSupabaseClient();
    if (!_supabase) return createSafeChain();
    return Reflect.get(_supabase, prop, receiver);
  },
});
